apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260504-235035-96a1cnwrql70-service
spec:
  selector:
    app: enterprise-system-20260504-235035-96a1cnwrql70
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
